server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: backend
          uri: ${BACKEND_URI:http://localhost:8080}
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
